### ISSUE TITLE
KeyError: 'FreeBSD'

### ISSUE THREAD

**Issue by grahamperrin** [naamancampbell/ff-containers-sort#2]
```text
grahamperrin@mowa219-gjp4-8570p:~ % sh
$ date ; uname -v
Mon 14 Dec 2020 07:17:50 GMT
FreeBSD 13.0-CURRENT #74 r368589: Sun Dec 13 07:55:46 GMT 2020     root@mowa219-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
$ ls -hl .local/bin
total 5
-rw-r--r--  1 grahamperrin  grahamperrin    74B  6 Dec 12:26 extract_msg
-rwxr-xr-x  1 grahamperrin  grahamperrin   244B 14 Dec 07:09 ff-containers-sort
$ .local/bin/ff-containers-sort
Traceback (most recent call last):
  File ".local/bin/ff-containers-sort", line 8, in <module>
    sys.exit(main())
  File "/home/grahamperrin/.local/lib/python3.7/site-packages/ff_containers_sort/ff_containers_sort.py", line 184, in main
    sort_containers(sort, manual)
  File "/home/grahamperrin/.local/lib/python3.7/site-packages/ff_containers_sort/ff_containers_sort.py", line 54, in sort_containers
    ff_dir = ff_paths[platform_name]
KeyError: 'FreeBSD'
$ pkg query '%o %v %R' firefox
www/firefox 84.0_2,2 FreeBSD
$ 
```

**Comment by naamancampbell** [comment]
Limited support can be added for FreeBSD if you provide the full path to your containers.json file.
Issue is closed as the KeyError is being caught now.

**Comment by grahamperrin** [comment]
Sorry, I don't understand; 

```text
grahamperrin@mowa219-gjp4-8570p:~ % pip-review --interactive
Everything up-to-date
grahamperrin@mowa219-gjp4-8570p:~ % ff-containers-sort
Unsupported platform: FreeBSD
grahamperrin@mowa219-gjp4-8570p:~ % ff-containers-sort ~/.mozilla/firefox/58ectoj2.default/containers.json
usage: ff-containers-sort [-h] [-n] [-m]
ff-containers-sort: error: unrecognized arguments: /home/grahamperrin/.mozilla/firefox/58ectoj2.default/containers.json
grahamperrin@mowa219-gjp4-8570p:~ % ls -hl ~/.mozilla/firefox/58ectoj2.default/containers.json
-rw-------  1 grahamperrin  grahamperrin   1.4K 12 Dec 10:15 /home/grahamperrin/.mozilla/firefox/58ectoj2.default/containers.json
grahamperrin@mowa219-gjp4-8570p:~ % 
```

**Comment by naamancampbell** [comment]
Added limited FreeBSD OS support
